spring:
  application:
    name: SpringCloudGateWay
  cloud:
    gateway:
      routes:
        - id: sentinel-feign-gateway
          uri: lb://SpringCloudSentinel:8002
          predicates:
            - Path=/feign/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8850

server:
  port: 8003

